
services:
  nginx:
    image: nginx
    build: ./requirements/nginx/
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wp-files:/var/www/html/:ro
    ports:
      - 443:443
    networks:
      - inception_net
  mariadb:
    image: mariadb
    build: ./requirements/mariadb/
    restart: always
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception_net

  wordpress:
    image: wordpress
    depends_on:
      - redis
    build: ./requirements/wordpress
    volumes:
      - wp-files:/var/www/html/
    restart: always
    env_file: .env
    networks:
      - inception_net

  redis:
    image: redis
    restart: always
    networks:
      - inception_net
    depends_on:
      - mariadb
    env_file: .env
    build: ./requirements/bonus/redis-cache

  static:
    image: static-website
    restart: always
    networks:
      - inception_net
    depends_on:
      - nginx
    build: ./requirements/bonus/static

  adminer:
    image: adminer
    restart: always
    networks:
      - inception_net
    depends_on:
      - nginx
    build: ./requirements/bonus/adminer

  ftp:
    image: ftp
    restart: always
    networks:
      - inception_net
    ports:
      - "20:20"
      - "21:21"
      - "40000-40050:40000-40050"
    build: ./requirements/bonus/ftp
    depends_on:
      - wordpress
    volumes:
      - wp-files:/var/www/html/
    env_file: .env
  portainer:
    image: portainer
    restart: always
    build: ./requirements/bonus/portainer
    networks:
      - inception_net
    depends_on:
      - nginx
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data


networks:
    inception_net:
      driver: bridge


volumes:
    db-data:
      driver: local
      driver_opts:
        type: none
        device: ~/sait-alo/data/mariadb
        o: bind
    wp-files:
      driver: local
      driver_opts:
        type: none
        device: ~/sait-alo/data/wordpress
        o: bind
    portainer_data:
      driver: local