
services:
  nginx:
    image: nginx
    build: ./requirements/nginx/
    restart: always
    depends_on:
      - wordpress
    volumes:
      - WORDPRESS_VOL:/var/www/html/
      - ./requirements/nginx/conf/certs:/etc/nginx/certs
    ports:
      - 443:443
    networks:
      - inception_net
    
  mariadb:
    image: mariadb
    build: ./requirements/mariadb/
    restart: always
    env_file: .env
    volumes:
      - DB_VOL:/var/lib/mysql
    networks:
      - inception_net

  wordpress:
    image: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    volumes:
      - WORDPRESS_VOL:/var/www/html/
    restart: always
    env_file: .env
    networks:
      - inception_net

  redis:
    image: redis
    restart: always
    networks:
      - inception_net
    depends_on:
      - mariadb
    env_file: .env
    build: ./requirements/bonus/redis-cache

  static:
    image: static-website
    restart: always
    networks:
      - inception_net
    depends_on:
      - nginx
    build: ./requirements/bonus/static

  adminer:
    image: adminer
    restart: always
    networks:
      - inception_net
    depends_on:
      - nginx
    build: ./requirements/bonus/adminer

  ftp:
    image: ftp
    restart: always
    env_file: .env
    networks:
      - inception_net
    ports:
      - "21:21"
      - "40000-40050:40000-40050"
    build: ./requirements/bonus/ftp
    depends_on:
      - wordpress
    volumes:
      - WORDPRESS_VOL:/var/www/html/
  portainer:
    image: portainer
    restart: always
    build: ./requirements/bonus/portainer
    env_file: .env
    networks:
      - inception_net
    depends_on:
      - nginx
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - PORTAINER_VOL:/data

networks:
    inception_net:
      driver: bridge


volumes:
    DB_VOL:
      driver: local
      driver_opts:
        type: none
        device: /home/sait-alo/data/mariadb
        o: bind
    WORDPRESS_VOL:
      driver: local
      driver_opts:
        type: none
        device: /home/sait-alo/data/wordpress
        o: bind
    PORTAINER_VOL:
      driver: local